### ISSUE TITLE
Diagramme MCD

### ISSUE THREAD

**Issue by RomainMechain** [RomainMechain/SAE_BD#43]
Notre diagramme MCD à été modifier, il faut donc le corriger : 
- Table spectateur renommé en Utilisateur (de même pour ses attributs)
- Ajout d'une table TYPE_UTILISATEUR en dessous de utilisateur avec : 
    - idTypeUtilisateur (clé primaire )
    - nomTypeUtilisateur
    - lié avec UTILISATEUR ( EST_TYPE 1,1 coté UTILISATEUR et 0,n de l'autre )
- Suppression de l'attribut dateEvenement dans EVENEMENT
- Ajout de l'attribut preInscriptionTypeEvenement dans TYPE_EVENEMENT

**Comment by LANDONNOMINECyril** [comment]
fait
